apiVersion: storage.azure.m.upbound.io/v1beta1
kind: Account
metadata:
  name: patinatestblob
  namespace: crossplane-system
  annotations:
    crossplane.io/external-name: patinatestblob
spec:
  forProvider:
    accountKind: StorageV2
    accountReplicationType: LRS
    accountTier: Standard
    allowNestedItemsToBePublic: false
    httpsTrafficOnlyEnabled: true
    location: eastus
    minTlsVersion: TLS1_2
    publicNetworkAccessEnabled: true
    resourceGroupName: PatinaTesting
    sharedAccessKeyEnabled: true
  providerConfigRef:
    name: azure
    kind: ProviderConfig
