apiVersion: storage.azure.m.upbound.io/v1beta1
kind: Container
metadata:
  name: test
  namespace: crossplane-system
  annotations:
    crossplane.io/external-name: test
spec:
  forProvider:
    containerAccessType: private
    storageAccountIdRef:
      name: patinatestblob
      namespace: crossplane-system
  providerConfigRef:
    name: azure
    kind: ProviderConfig
