apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: production
type: Opaque
stringData:
  ADMIN_USER: ENC[AES256_GCM,data:UtaF99xZZQ==,iv:0bFbQixaAX8FQ8fSpLqJRICHUqTzt93gKntR23Ckcgs=,tag:WiSmdEMWMuk+tZbchv1LMw==,type:str]
  #ENC[AES256_GCM,data:43FdNP6729HqP9E4xtbTqgFCWS7qimYkRHHIXNPfMegbiXxwu/yhSrNHutDVqlMpEycPlUvF73gQlLc0OA==,iv:uIKe2lb6hJQNeTKoNJoa2WonUiB88UxPLzWPblzKMVw=,tag:0NzebKULikGWB9c/OIp4KA==,type:comment]
  ADMIN_PASSWORD: ENC[AES256_GCM,data:e03aEZB8jaKyXG49ThsZEQ==,iv:AID7w/STz79kLvNU5jxblAb+ijjofzMnzO65ZHWy/Kk=,tag:vk8GBAM66PhLaq7jPLlrKw==,type:str]
  DB_USER: ENC[AES256_GCM,data:HJfaT/HivFsjwA==,iv:eI37z1e+RoRMRCEXAaBdh+CxpBHd6JMgehNHGOKFueg=,tag:5IZtnNrQ6GWmtbmN7ZVUKw==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:2z8N7CORQLZDV1QqcwLUeaNyi9qGY1MSIDLv+gj057U=,iv:luKb0+wUTE7wv1S2FsSSOX4kJtpTLwKZJXsmmHM/+oo=,tag:UM6emLX7dayyqVsNwvzWvg==,type:str]
sops:
  azure_kv:
    - vault_url: https://sops-master.vault.azure.net
      name: sops-key
      version: 90784f2986de4514934b4d1f682d3e59
      created_at: "2026-04-15T05:26:09Z"
      enc: HRBfKkdArTqGBnyOksanaWAXheIs93YMwql781mdASWIqkWVM_H--6btPMSq6f8v8086W2Qn2rF1srC_fq4NvFvr3IRzNOhQZ3h6cUuPX9M4pT1tFfvY4l6OvHDRzeZp33UgnkekFFU6QW5OteFli7dlz9-jeuClEu7bx2K-f-MvSqVZVSK4T8q31yHPOSl7ImrFgFVrpOgxJJwa5UudjJ8lU_h0qHsFDA7LV6VPqoz-SU6lssSdA8jNeEQ0z3Np2MwS4l5wsZLFPKGAzobCspcJ23uM20rexc-Ofef-qRcjxQfU0C0MYKeQiy2YyEjrXNjGpjK8zkOgVv-KO6BzZQ
  lastmodified: "2026-04-15T05:26:10Z"
  mac: ENC[AES256_GCM,data:dPGksCE9XRS5M+dIKOSr0myk/cg24LFu6txmQX+48NWbzoImYHOleaAU9DgXcbNkJhAzIRA9rQJep9a3eD9B+weLITS1eI578wR+YODj22EU+NlAVYddGUJGh1yxgGrrTh15dmi1T2ZQQG7V8RrssPr1hiscM6C0lVZniX9BoI8=,iv:OdQVAYrrFZScJrAk1T2ZV2KKM4B9M05CGmA8mSgoi8I=,tag:SJNJl6CNNhkrj1Z0sWyzdw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
