apiVersion: v1
kind: Secret
metadata:
  name: codebloom-standup-bot-production-secrets
type: Opaque
stringData:
  DISCORD_CLIENT_ID: ENC[AES256_GCM,data:C7uBJkiC5q4/US3dzf1AlmNuiQ==,iv:3CV3fm9bK+VnqXeuzLSCZc8jlCNauxbNBRbGrOXSANw=,tag:G31buXKNjZxQvS94X51xNg==,type:str]
  DISCORD_CLIENT_SECRET: ENC[AES256_GCM,data:lM/n821/i01VadP3rKWJ8uV5TnUWg6WLc26tiq3bLBI=,iv:cTJkyKoJg1iNDXXlTyDR3vLL+dHBxOpkMegxY9aFOxU=,tag:ybA3hnJamo2obGrEVrIQBA==,type:str]
  DISCORD_TOKEN: ENC[AES256_GCM,data:NSXSz15CMcWt06N9QXf3Jjgw7rYuYDniyRUVwleNfxviFcbQ1s5PD7XRaygg6AIntG4Qs7dG3IfKJNwr0ue1oYU+7tnp/fPN,iv:i6qnKkj1OIp/U5Ppbn3PQQgHwn57/+71bdKyeVQSnRI=,tag:lqm1K1db7ik/GkP6dWXUBA==,type:str]
  DISCORD_GUILD_ID: ENC[AES256_GCM,data:urDVihzfB+qJxP8BIo9+QQc6IQ==,iv:fHHrGkIj+OXmVDHwGFdEp3miDyR3V1CQMnRus6yAW/A=,tag:gVIVfYOTc6SkeFsdqZttuw==,type:str]
  DISCORD_CHANNEL_ID: ENC[AES256_GCM,data:FJ7qpvU5C141Wz0Q8ZikzYwp/Q==,iv:JmS8SFkeMZoU6hFwMJhDhSFDh+zLEKvuLX8kZUp7zEA=,tag:LlWTPTPi6ODd/LqP+2caFw==,type:str]
  #ENC[AES256_GCM,data:omiHBHj0Ez2vlgg4iamTlKdc9MKouI7eetUQbv4PEQ==,iv:nW4yHGPlOXsppVB2GQm+S07Xh23QXAB+cpoZt2MibBY=,tag:OQ8IoXSS4zKtmQApIgH0Mw==,type:comment]
  REDIS_URI: ENC[AES256_GCM,data:dMsmE/2luQ6W/po/oIaskfsJzX8r5pTTDLukqJaSpD6277EBZAGG5RW9nymPb2nGg06fJzk+d/UDZFkMQrfkRc/0801aPv7NWFp6fhWU1ELhKyZCYXVOeGTAnsSolSckEJOViVnQgg==,iv:mAY4JrQujXwZYnBQCGi51MK9mmpebbr2EvTWuk9TVxU=,tag:SnhcJe6p5k3fqR/DCQ/fFw==,type:str]
sops:
  azure_kv:
    - vault_url: https://sops-master.vault.azure.net
      name: sops-key
      version: 90784f2986de4514934b4d1f682d3e59
      created_at: "2026-04-25T22:54:07Z"
      enc: aRxok1UIb0yUnLIVFoG1TmmjFUULQK6v6Og8_czWH9DqbaPmWQWMg0jlyaWAjyEyDyLPAAV08_bKfTAqoFHL8fCRwPQtjY-xrcOKjwVMF8kNHMB39a8z9NudRukWtfWm1Wvfv2YxmufZHNqv_cFZP0878G97tLpTN3-MJxOyzbZ0H1h9Ji4qahlH9_bMCOFEQCYqmGxPEazbTVyaWqrBXsFpulGNATTu7x9yitTjYGirSuLM8S35JWhDVimsM34XUfHWoSO50ukNEEA0ZnnZHOXOm-_Rt7MgV8K23YTNXKBPfCWaKKyP8u7Ep8tL9HzS7rYO8DloAhnRkpqV0aIC6g
  lastmodified: "2026-04-25T22:54:11Z"
  mac: ENC[AES256_GCM,data:TuQ8+NdlFEqtW3CfQZ2phIYkcQJFzBKDBoXtrwiXu2b1b7ShrVgsnxyMGJvbZePssCW8RQ5Nz/18Ze9Mo8kKaVS69a+zbDOlPI26fYedLDysANFXN/et/ZWY18K+6ei2Sh9k/8EPCVwC51WpGqgz8Fo8A7IbHPCv7DMCz/8g4aM=,iv:0pKXI1lH1S29/wlkrXN6Nk5CwQ5JsbDPdROKVLnzCrw=,tag:5FtiSYWE74BBumgG7T6eWg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
