apiVersion: v1
kind: Secret
metadata:
  name: codebloom-standup-bot-production-secrets
type: Opaque
stringData:
  DISCORD_CLIENT_ID: ENC[AES256_GCM,data:TllGDFmWQ4APNpYNU7R/zL/8Xw==,iv:LRBZEb+PFg8AHP3jdDPro0eKw99uha6UiLIvAToOaOU=,tag:Ps0SEkmmk4sLGklIyUPcBg==,type:str]
  DISCORD_CLIENT_SECRET: ENC[AES256_GCM,data:9v5r9Fwwe9ijUdgMxn+vIWVP4GjFFjyPtRA8JhX7yPU=,iv:RrXU9jgsZa5q3G8XIcugXu8f1lCBgkSrxQZpVvtstSk=,tag:ezeE4X3Sp8XhlD7UGOKsJw==,type:str]
  DISCORD_TOKEN: ENC[AES256_GCM,data:iKW6OGKc2j6ln4Cjr6hZdDSUaeit1exxout+gwb0eT3Y0oEeDd8MgaoLeACGOKRRGRoP9ZX59M3EiN8yXWAiXOqiR6LG6QHH,iv:JrYSxgyEwWeAGdHD8g8Y5XzFuG/RTsNkU/DvTkBODa0=,tag:/ZajarVZyLYwxoBfOg57PA==,type:str]
  DISCORD_GUILD_ID: ENC[AES256_GCM,data:9/ivRxVT34zpNzJLMx2TYOWXvg==,iv:QFs2vDis/pEG+7Lm22tRP/ahgC6FIaX82VVJ8NfF4LE=,tag:O3v8+BJ7Q5HCJTXoZGb19g==,type:str]
  DISCORD_CHANNEL_ID: ENC[AES256_GCM,data:UTCK6H46G/CCaOl5s+6UFA0+Gw==,iv:BVBXs77arzI6/NuMY0Cc+c9Vmin2q8fWPzuaHXggnLw=,tag:M0F0bkDxaglH+0/l6vl9QA==,type:str]
  REDIS_URI: ENC[AES256_GCM,data:01lNx7agyhwMDT8/U///OLf29tref+yqombV4UP1jZl4zwTsZKiTkBnhs/aza2FAISgdhSfiiUe6Fq+Hcd4rCRpdAID/GeGzuWT4zITdOvzwo2CwQJ36xdGNL7Jm4sh6,iv:W8GdEXg5yY6dOGhIdsSCSg0w1/t4Jbzl2txacDKwRIY=,tag:zp6Wwg5qtMrrRE787kX1gw==,type:str]
sops:
  azure_kv:
    - vault_url: https://sops-master.vault.azure.net
      name: sops-key
      version: 90784f2986de4514934b4d1f682d3e59
      created_at: "2026-04-27T05:52:49Z"
      enc: ZK3dVFutRHV1sdmDu7D_OWjwGVhdwsYPYXH4imGw7Jodo9SlIn6k5YMIFabFg3pCOlYHFEQ8irX3mbQ5AIMjl2qf7-BBZnBn6l0b1OOOaQBBS85J4D_wPdNo8uqMuGDNyeTo6p_E8fCDwLxB_mSVRcKdY-IIV1N-0m_vetipCyXC1k7E46oaE6u8--8za_yxPqFeoaMzIBGgMK8rOFin_nS6_keXW3vENxjURxfdThosP93W8UPsWO6ywwldiyWaFXvQMnoM0jSnF8048oa_caaSXwk0qppCyJv_Nv6OtKMwvffafIR11HCEeVmzOBpK1ynooxyo3gl-ZU12DWtDMQ
  lastmodified: "2026-04-27T05:52:52Z"
  mac: ENC[AES256_GCM,data:nQaeeCF7iCPgNqIxt8vUr9L9laYM/12ROOvSwPw7WqA3kRX+Zmy0HTJl8I/2umhw4jvC9+55sZwVv6SKcyPihpbwVQZg5CbdRMkR3/hKtHDUFYFWyzNpDGNRQNf45J9CtN3Z/XlMdF4uHAEowXDXYi4Lv3G0LSHuWDmLvhocAQ8=,iv:6pKFLCheM16xYpWDAz6ZQlJj8F+GWvEDi4vuYSf03JM=,tag:eYalxARRUPbCyV1Qg/PxZQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
