apiVersion: v1
kind: Secret
metadata:
  name: codebloom-standup-bot-production-secrets
type: Opaque
stringData:
  DISCORD_CLIENT_ID: ENC[AES256_GCM,data:KbCjHRsCMUYnfykVj/GIMYlAXA==,iv:cq0+NHu3wng2RXLXukXB5RUCresnchq0VkZZkfFcBlQ=,tag:2dyPHFOO8EdGFLua4Ce2Xw==,type:str]
  DISCORD_CLIENT_SECRET: ENC[AES256_GCM,data:zR3r2mFqhUa2P+tvdzlROx8NJMAtpy5T2qapLRYgVPE=,iv:UVzVdFnlukzWVqhbQ4JJN0AUqz02X0nQ5sbvNl0IfMM=,tag:h2ltn21g2cEo/ubRjGej1g==,type:str]
  DISCORD_TOKEN: ENC[AES256_GCM,data:d+twwEQWlmJeQy8EyWwc4ZYpiThXE3OqrTdDDi+rPXWoX7n2wuVPrKDvUTTgeHxSLrm/LsSVND4DDIpnAqhX8ADmIOVFgbOy,iv:ZtVyIolEy3DWeGpyPxUB5JMcTPhmK69H0V0ZKUPFeEo=,tag:MznrAkcmnGNJwJWYDL3Vnw==,type:str]
  DISCORD_GUILD_ID: ENC[AES256_GCM,data:N5p7mNLjYN3Utf4w8szb50u/Uw==,iv:giLMC3UYxDyoa6I4fZWcLHyg6dqR49AsUkM3CMYA26Y=,tag:7gZ856T710fdj+DRTWUdqA==,type:str]
  DISCORD_CHANNEL_ID: ENC[AES256_GCM,data:7UKlNlUMhP4LKF9AJ+Qq1ABqiQ==,iv:DB38S173srKuo7BAC+XgdpydW9WRbuJtWFSRUEKx+6U=,tag:PuvZYXOGcUv4p4iCEBaRYQ==,type:str]
  #ENC[AES256_GCM,data:GOq+xuecmrI8CycAq36kxMY7SbQ+AeqZAAkCe/u/8A==,iv:gkdZNxgXJJDfsNoZa7+OxRsx416Uidl8RZ9RvsrZeVo=,tag:0qZeRvajLQIhewv6W6+FpQ==,type:comment]
  REDIS_URL: ENC[AES256_GCM,data:ta0DjvmbIxtVDQOc5yvV61qjdOj/xcBlWq8So9fCTwk9iFlxMNaHA7xvT7snqGrtEY9nP4XB0/Whk62WHAsT74k2ox5YTVNuIuE+SDcUjySQxDaWmb/Da2o/4gXn0E/UlDDV,iv:hgJqo3+I8YRnh6aRfJndXg/J8MPMeXOYDg23J+Irsgo=,tag:jd+Qf9jok/YZCgCOsP9xfQ==,type:str]
sops:
  azure_kv:
    - vault_url: https://sops-master.vault.azure.net
      name: sops-key
      version: 90784f2986de4514934b4d1f682d3e59
      created_at: "2026-04-26T01:47:06Z"
      enc: D5MiUPOsAQ3yr5z3GY4piP9n-mEbm3czAOsoVbB8Ax6vAbadXqA4GgvhZAl8kS2ApNgj68njS6jVnzGk2KiX4WFDQGRPwGOJ9DdUGCrBkHrBZ4T98pncZ24C5wKPpBxXACAeGcER19y4RjHCuN1XDI5tJoYibmWajEowPzCAtaW-_QE4iJzpzwjPeasXUGrYdJ2jtfmrcqk1LAShUMKpGBF3IU7ScG7vh1jzdqo9P5qmKBKnsaMVT8LujRoDHwgxyP3Ms4wvpP0a68deNx7hSzSWq1CgvR_rFG1-6PFOZ6NZonxaEgw4Ixc_DKi-ksiagtsOmXQXytl_Jog5h5Eosg
  lastmodified: "2026-04-26T01:47:09Z"
  mac: ENC[AES256_GCM,data:TFDe8Z17VpCnnhe+cCw7FLb5th1QcymVAkYdodZKplihBhrPgd+BaKRkGgbixMQV8SXFF3tc0+H3MjBvxtSDevd5LRIdwRqrgkOZ4jMTBCSnUGvkUgly+B7pAUgB9tzgFluI1i3+jJPVojWi1x2sMuT2u04VDSMJ/scHkkHAIvA=,iv:sy0xW/yl7dWKre9Ut5NXbfmpZA4v25aDtuyEqSbfzHM=,tag:CunR9/ie5bzmqL7RJEIMcQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
