apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crossplane
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: crossplane-system
  install:
    createNamespace: true
    crds: Create
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: crossplane
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: crossplane-stable
        namespace: flux-system
      interval: 12h
  values:
    resourcesCrossplane:
      requests:
        cpu: 20m
    provider:
      packages:
        - xpkg.upbound.io/crossplane-contrib/provider-upjet-github:v0.19.0
        - xpkg.upbound.io/upbound/provider-family-azure:v2.5.2
        - xpkg.upbound.io/upbound/provider-azure-storage:v2.5.2
    replicas: 1
    rbacManager:
      replicas: 1
    resourcesRBACManager:
      requests:
        cpu: 20m
