# override any Spring app properties here

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

server:
  url: https://codebloom.patinanetwork.org

management:
  endpoint:
    env:
      # /actuator/* is pwd protected so this is ok
      # show-values: "always"
  endpoints:
    web:
      exposure:
        # add beans and env
        include: prometheus, health, beans, env
