apiVersion: v1
kind: Secret
metadata:
  name: postgres-creds
  namespace: production
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:BIixEHJZUNY=,iv:Q8Ir4Ws3SZ97stQMSknMvgClbQQlFBob9iEzAw3q51M=,tag:zIXH1yg8flDtGysWNjfbvg==,type:str]
  password: ENC[AES256_GCM,data:4H9TK+VnZ6a/LAzkassZNxJNP/odTO1wrRHB3wuL,iv:RtrKB/Fje42YUfoI3cPL/bbqSI7wC6VbHjhW2daabZs=,tag:XCPH2qxyl6cjCs2O7D/lHw==,type:str]
sops:
  azure_kv:
    - vault_url: https://sops-master.vault.azure.net
      name: sops-key
      version: 90784f2986de4514934b4d1f682d3e59
      created_at: "2026-04-12T01:35:54Z"
      enc: eobzPpTXJuR1nP7J0rMRw1_2sp5kcredK3oZfKcn0NuSIbrHms33DXW1ke0s-0x4YibF7hnTzBMCiSVL50Kh9RHVrnhcDs_pgk96dWWiZ3hsrX_Qe79LvlQYvlR0Yp6s4zjdBws4sIRRD7qekKdTRFyVd8oIV7rLRd87W5qORBd8Q3ZUz19bcDmoO1SfLeiJS2QtGwvx1vx4NPzBEt2TFU7jdy3n_koplBkspRKw13-LsSoJ0Cpk_tyT2uLk61fzW05s6m1m6QuUOEm44dE3hNAlaaUrHa7s5-bwlwq2QnccU6v1ZJP9ixuJXG-M3mIFY3dm22XTpoxJS1gs3rGYHA
  lastmodified: "2026-04-12T01:35:57Z"
  mac: ENC[AES256_GCM,data:wiRw/u+sUtnlEGOcznqCRogToNMWiEFNkPhI+mdbplYI2nqwz0DzBhlMs7ZLRqv/AowzR1cuiHodwDaWHpjemm0wvNWpWEUHxeJ3WW7NdGTrGJrtcpXJJWp9cxekayI4SS/VFNc0ZRJhUNZmcf+Kf5GiZiFnv4v6DQdPrj4AWlI=,iv:PQobY5IntADGCvz9ty/yLXlx9A1YoYxnqZqRRBzU+TM=,tag:mTmZQXp9Hd/BiFrf3X8JMw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
