apiVersion: v1
kind: Secret
metadata:
  name: redis-creds
  namespace: infrastructure
type: Opaque
stringData:
  #ENC[AES256_GCM,data:7AFl76QL8C51co5hk1Au7wIf6rRZHD0ay8c4nDjRPEfdji/aLA2SvM5s3qWmSqQS5YlI+bfnPH+sFxI=,iv:3tZlE9A73Erz7zfE0cssL6RhnpETostbJjack9lllRg=,tag:kkRKgwaXsK8UUHCPatYyPA==,type:comment]
  password: ENC[AES256_GCM,data:aZyx5Sr77wsxLDqfWJDD9kFMDNg7ePUpociFIqb1NPM=,iv:U3gZcptIp+7UsCO1xIK+evE1H6kLog5woZ9y6s2VKPc=,tag:vXTaM4ra1m0MCW8QY4CKoQ==,type:str]
sops:
  azure_kv:
    - vault_url: https://sops-master.vault.azure.net
      name: sops-key
      version: 90784f2986de4514934b4d1f682d3e59
      created_at: "2026-04-27T05:50:20Z"
      enc: FzldfKlIXcUAYN-O7XEw_5M57Og0-9_JLlcroWK_GQO6uxubVi1m2jPXVO3sA_Hlh_gBZCOfC5Xyhd2oA-RZ1decyOLvAnAHdalHmYYBqLlmCzHxfQwggsixPI5a2MUzIWLJS2YczmF0b0ANp8UYGA_A0E4VT-UAEo2ZBGspXGWwcYYpeXikUzjPsDmS_i9kQcVN-PloR9s_mdQmZ1DJdz0NCRKngi6KOAiazIWxHgZhdSaKQaisJqxRuSQQWkqNhWMKJyhqB4C-edSDFtXICu-DrlWUwTqyCRyV2IlAK56x2Odf7O3wEOcTZUfW900h_JlQARFbagNNsRFdajFUHw
  lastmodified: "2026-04-27T05:50:23Z"
  mac: ENC[AES256_GCM,data:aaRATHeIw3nEqKgolt0NBaNwXW+IwrRNOawnPeCpwZF05zp/l6/c/kuoYG+qRwrfMehrWf/Tg+YAKsFdO+mhnD0YedvpXyUsCXO84VkA8KTznevnd77mVRnGY3+zvqeMqKGb+mhJDZx5Kz9eNC5sYFHXYvbfr2zD8JtESkvxEhg=,iv:mE+bBRTRzDgc9iJzzJYHnNVmFFTQGu42XpT5QZMJ+Zs=,tag:gltit2n5bp2V5etquiEHng==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
