apiVersion: v1
kind: Secret
metadata:
  name: redis-creds
  namespace: infrastructure
type: Opaque
stringData:
  #ENC[AES256_GCM,data:425ZOCr3PUKeFGL5SUacHuxp3mcRd3ySSBlI/boBcpoiw/yDySSGpuQ+DJHtgWiHgxusZG148FkUQfs=,iv:/4RN+df7oNUZDBS/HcvfDod8AvdlYxxCjI4n/WKprNc=,tag:JIRTQQTgkjn/V++2uAZnyA==,type:comment]
  password: ENC[AES256_GCM,data:KwvHR5aQM0+SqhZDWWgfPrT2Od26BO+yJy3J0y26K6Y=,iv:IaJJvXYXc6Mmg4IP/1Q4TnfeL0teqyUNp7ehRyeyyMc=,tag:wCP8Z5FU2t4jpiZ9zlh9Yw==,type:str]
sops:
  azure_kv:
    - vault_url: https://sops-master.vault.azure.net
      name: sops-key
      version: 90784f2986de4514934b4d1f682d3e59
      created_at: "2026-04-25T23:37:32Z"
      enc: AmM4_BqvTEGPwXDK084DpO4Abys3Il1yly-41k9txsYBBGONm7mFX9-tnr2x8wBiaBkszZJp4lng2TUAXNQyTDsNQnogurqEG_H6Tp0RBcbo157G7B9_1ISaKaqiVe-RqwxMp5ZWGon7uBUAriSj--b5_wSLTTMko6hxxvyqylmNqxOGN9Ll2EUvJLuYFqQW8Z1Z-7bN-2z4ofw-roOWcO5aFyTnk8MpcvJpuvyq5WLasgLvFHO0_o3xIBiQiOxXEEX8rQsT6zu5X89zIUR08GW0KTWC7V7yo--LyTGU--Vx0Vt34PiBfkpkbDBjslpaX8qeAbLI0AnHBcjQB6Ks3Q
  lastmodified: "2026-04-25T23:37:35Z"
  mac: ENC[AES256_GCM,data:3ayo0mun7xQUGqAQNwlVy9euH41zaU3sHAlonB+YCwemMS5kyiVuHX/x8xQyZVPCqEWzkxMmpSltP0xwmBx0Hz8AG+0T1lJDy98mdhKEY5NcPpzY8TcJnQ7xCjt9dakNG9DGHN+Fmktbc4H0BgpB0uzq/WBFFk5F4buPI69dkb4=,iv:3d6kHgJGVtCpr52hRK7J6n9GyuMaQ4ZcnBUELfPwI2Q=,tag:a5ehbwRDYz7Y/Bod4IDisQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
