apiVersion: v1
kind: Secret
metadata:
  name: postgres-backup-creds
type: Opaque
stringData:
  PGUSER: ENC[AES256_GCM,data:+zU5r0jHtbY4tlYQEESb,iv:Nao2pQghhlgGtVG16hrXqaAZ6/wIq0ENDywQ1CttBHI=,tag:2sVXy+C149r9OJ9J/U3+6A==,type:str]
  PGPASSWORD: ENC[AES256_GCM,data:W6zr8r8n++CVFLbJvBCdeAjVRID2mzBckeVjc3CVJhc=,iv:71Op78JgD70ScglsRjjHCq1T1aJbEMLSKmVTvrakAbI=,tag:7BLZ8QF2UA11DP/H+tD47A==,type:str]
sops:
  azure_kv:
    - vault_url: https://sops-master.vault.azure.net
      name: sops-key
      version: 90784f2986de4514934b4d1f682d3e59
      created_at: "2026-04-23T06:12:48Z"
      enc: tkEiYEDarIuJKh-BWo5Gs9dA3pmm94kaT53P5bHGDXgsV4UP4AfAyIYiP9i3SmAmz6QwCUxZz5J2j6C4otmi8mSeaBZEotvCAKtuVKPrmseWXQBS5RnTkLKQA4bA4dENcmpWU7cZkjVak-_KSQjgk0QjAOUNd-uPMfY5Pb31ghVsp4_NIFZLgKWOBNMP2m-BmRvRN-OEpE_PfMy8-cE15EtgkBqEthCsl1GaMDvuqAUCzKY_HKev7C9uCA0XhHnwujR-U1-RSSevqYopqjrdMOCnQTRCwZxz7WICCgjR_XXAJtyxHJg-_F7DuykTK0z5zEWMrAESwWbEBpWHUWwj0Q
  lastmodified: "2026-04-23T06:12:51Z"
  mac: ENC[AES256_GCM,data:VCv3VeixV8bjZVn5zmeGJHHwuT21b2yKOuBREh4h2itrZnsgCUnMFJUU5PezR/vOTtMxM51V8POTi879driPr1kEDOx1fgyQ0zWwD0xXFRcbEV91hsY8HSvXjTWDG3Bz1XaYSMO0eQraF7ma21dLZUjnXgSpv+L0eSMcx8mzXeE=,iv:x5kkFutJc5L7xA5STqfH+nl75KTE76F9Hp65lZ7JgZc=,tag:wvvNlQ+X5M8MooZck2Xtyw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
