# override any codebloom properties here

#TODO: wait for Codebloom to move scheduled to a configuration
# spring:
#   scheduling:
#     enabled: false

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false
    version: OPENAPI_3_0
