apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: codebloom
  namespace: staging
spec:
  selector:
    matchLabels:
      app: codebloom
  endpoints:
    - port: http-web
      path: /actuator/prometheus
      interval: 30s
      basicAuth:
        username:
          name: codebloom-staging-secrets
          key: ACTUATOR_USERNAME
        password:
          name: codebloom-staging-secrets
          key: ACTUATOR_PASSWORD
