apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: infrastructure
type: Opaque
stringData:
  ADMIN_USER: ENC[AES256_GCM,data:R67KxnCdtQ==,iv:LxltGRXjdklqF6S/J6K4oCa3Blo9v4NSzwg96Z+HwUs=,tag:oG4a9FbRwF8oFkeW0H8puA==,type:str]
  #ENC[AES256_GCM,data:gqKqVlE4FKwn1LhfdT+jgfComi8ClgOrkOBRPMs0On5qUaI9mUvhQd3EWpMlsu8AycIQimXVNd88fa6aAA==,iv:0RBmOG6OB84KN6hWS5SQanN4dzoP1bx8XLqoPa667f4=,tag:xTk+9niQxjMqCMqLatSK3w==,type:comment]
  ADMIN_PASSWORD: ENC[AES256_GCM,data:WNIKl4LoUmtih3wyTadbaw==,iv:vEA2mS37BpU+LbNIr0L7bOLb3CGWjez5b8+Xd8MCVJk=,tag:T8JZ5SB/WBI8DZE9thGOTA==,type:str]
  DB_USER: ENC[AES256_GCM,data:cg3n/uDw0eoYmA==,iv:Z2Yov3ixZAwKbN16f/UeTpPF2uImz+irHwaVHLoTSJI=,tag:87uZGJGd6WmcCJnqjB1U1A==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:MPOyxW+DHMcjW+LFRjEqNKGBWF/+XgoN67Iysz3uaB0=,iv:lquMGSmlK4GQ6oEwdOO9xgUoXZAW79/n+k6iC1YBpvU=,tag:fu8rReree4TYz2mh7uLayA==,type:str]
sops:
  azure_kv:
    - vault_url: https://sops-master.vault.azure.net
      name: sops-key
      version: 90784f2986de4514934b4d1f682d3e59
      created_at: "2026-04-15T09:56:11Z"
      enc: XygGioSZehBYyFBnBQmv0zgoHSHdy2MqFwS1diAPPattf2847noFlTQIC3ZT4b-7wFezv6cPsEH2tHrC23JsxDzHm1sZisJVVKQmUSNIuuz20C7tCyiwmEImItCW4aVM9nfba90ibZseH8x75QIIaz7uTgxZuDpZgS7BsdLYDeCY96tCIreSyDn6LHtBxmaKsLh5WBu1n4Sgsp_QTJmxnlerRvdG96MuZrC9bh3KZHKcoqco_DcoM2ClBjpWclIJxaNS475cd6Gtjcaktf582cc0_JRTFAFTDC6dFcllx5PQvcxD-JJxwT2gQVMxbMJTY6EPltjDKPzEttWEl7_xPQ
  lastmodified: "2026-04-15T09:56:14Z"
  mac: ENC[AES256_GCM,data:ZWjaeJ0juOnWQ5wsHLC0q6zHdIkrPPEREbDz2hi3qAqNhMruKU3bZzaUQxeoRF1Y3kYWpMtbaJcqD99ctbw63uASO7QCLmYYhui1KcqL3mlXUhLwtWog+jndoAeWB4rUEXwm2ZsxHdBjtq/Lh55Gp/i/LAXzDFkLggbKxLmEPIs=,iv:JLC/U+4B9f4F6+C/zSHlqXT04Qo2j5D+CjwYM3PNIRk=,tag:TadvZU0Y4ZbWQLaPjzvozQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
