apiVersion: v1
kind: ServiceAccount
metadata:
  name: kustomize-controller
  namespace: flux-system
  annotations:
    # az identity show --name flux-kustomize --resource-group k8s --query clientId -o tsv
    # this is managed by `platform-infra`
    azure.workload.identity/client-id: 0a3abc4e-ec0c-4d46-ba29-4443e7f8946e
    azure.workload.identity/tenant-id: 88e5fbad-e2c7-474e-a963-2fbe9a0bab8f
    azure.workload.identity/service-account-token-expiration: "3600"
  labels:
    azure.workload.identity/use: "true"
