apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: github-repositories
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: ./environments/infrastructure/crossplane/github/repositories
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 12h
      reconcileStrategy: Revision
