# yaml-language-server: $schema=./values.schema.json
providerConfigName: github
repositories:
  example-repository:
    existing: false
    visibility: private
    maintain:
      - "@Patina-Network/admin"
    write:
      - "@Patina-Network/dev"
  k8s-universe:
    existing: true
    visibility: public
    maintain:
      - "@Patina-Network/admin"
    write:
      - "@Patina-Network/dev"
