# yaml-language-server: $schema=./values.schema.json
providerConfigName: github
repositories:
  example-repository:
    existing: false
    visibility: private
    read:
      - "@Patina-Network/read-only"
    write:
      - "@Patina-Network/admin"
