{{- range $repoName, $repo := .Values.repositories }}
{{- $repoResourceName := $repoName | lower | replace "_" "-" | replace "." "-" }}
{{- range $teamSlug := default (list) $repo.read }}
{{- $teamName := (last (splitList "/" ($teamSlug | trimPrefix "@"))) }}
---
apiVersion: team.github.upbound.io/v1alpha1
kind: TeamRepository
metadata:
  name: {{ printf "%s-reader-%s" $repoResourceName ($teamName | lower | replace "_" "-" | replace "." "-") }}
spec:
  forProvider:
    permission: pull
    repository: {{ $repoName }}
    teamIdRef:
      name: {{ $teamName | lower }}
  providerConfigRef:
    name: {{ $.Values.providerConfigName }}
{{- end }}
{{- range $teamSlug := default (list) $repo.write }}
{{- $teamName := (last (splitList "/" ($teamSlug | trimPrefix "@"))) }}
---
apiVersion: team.github.upbound.io/v1alpha1
kind: TeamRepository
metadata:
  name: {{ printf "%s-writer-%s" $repoResourceName ($teamName | lower | replace "_" "-" | replace "." "-") }}
spec:
  forProvider:
    permission: push
    repository: {{ $repoName }}
    teamIdRef:
      name: {{ $teamName | lower }}
  providerConfigRef:
    name: {{ $.Values.providerConfigName }}
{{- end }}
{{- end }}
