{{- range .Values.members }}
---
apiVersion: user.github.upbound.io/v1alpha1
kind: Membership
metadata:
  name: {{ .username | lower }}
  namespace: {{ $.Values.namespace }}
spec:
  forProvider:
    username: {{ .username }}
    role: {{ default "member" .role }}
  providerConfigRef:
    name: {{ $.Values.providerConfigName }}
{{- end }}
