apiVersion: v1
kind: ServiceAccount
metadata:
  name: production-sa
  namespace: production
  annotations:
    # az identity show --name production-sa --resource-group k8s --query clientId -o tsv
    # managed by `platform-infra`
    azure.workload.identity/client-id: 4291ac07-f405-4792-9dc6-24d2ec8d1053
    azure.workload.identity/tenant-id: 88e5fbad-e2c7-474e-a963-2fbe9a0bab8f
    azure.workload.identity/service-account-token-expiration: "3600"
  labels:
    azure.workload.identity/use: "true"
