apiVersion: v1
kind: ServiceAccount
metadata:
  name: staging-sa
  namespace: staging
  annotations:
    # az identity show --name staging-sa --resource-group k8s --query clientId -o tsv
    # managed by `platform-infra`
    azure.workload.identity/client-id: b33410b2-3365-4b2e-a755-3c419bef28cc
    azure.workload.identity/tenant-id: 88e5fbad-e2c7-474e-a963-2fbe9a0bab8f
    azure.workload.identity/service-account-token-expiration: "3600"
  labels:
    azure.workload.identity/use: "true"
