apiVersion: v1
kind: ServiceAccount
metadata:
  name: infrastructure-sa
  namespace: infrastructure
  annotations:
    # az identity show --name infrastructure-sa --resource-group k8s --query clientId -o tsv
    # managed by `platform-infra`
    azure.workload.identity/client-id: a79c2ae8-6c3d-482c-8204-e73dd4076275
    azure.workload.identity/tenant-id: 88e5fbad-e2c7-474e-a963-2fbe9a0bab8f
    azure.workload.identity/service-account-token-expiration: "3600"
  labels:
    azure.workload.identity/use: "true"
