apiVersion: v1
kind: Secret
metadata:
  name: azure-provider-creds
  namespace: crossplane-system
type: Opaque
# Mapping from new az ad sp create-for-rbac output:
# - appId -> clientId
# - password -> clientSecret
stringData:
  creds: ENC[AES256_GCM,data:gjLokE3AmMOmaA3p/mgGjIPAO9iIHGO8xQqA8zhefLgTUNXWlIHzuGuU6sQY71BJbSFR20S3yNqNprZBCP1FI8XL7CcERiWw2LNdAMaJCgqlv8ogLDPT8uOqY576/XwwUb8oOoT3l1GC2GJhOdtKZLeWppiRuOl0rACmZgEfCXZA+MyEpOj3g01OXZoQSKwVyPFTnvYTuvPwuWxnbirofi+GEC7YudcY3e2L34oFQYE8zo7IrTZGXxZpFJqarjjYHlFMN9j9+cUFwCF7DDqkHl8Sl2EhKAuKvlSHLernCjZABhWmuSXfEuPJsc7L1V51KYxWke1jLcft6zkOtu6YBVhTQ1v8nbrHWEa+UjIECswTlATtatRtrYrDRlxWbX6Lv981Vmdjg+YgBag7juAvjW1sO7aWUWna8gnyVK4S6xu3hbUz8Gve6GQw6mSIDatv+wNoIj1AC5P+8fkFIITzq2+vXLWu9/Rxj07iUJ9M4+2xAeneC0lQVQhwJZ+Fff0EgoqCyQfjMlcnKYu1FeDHpf1JGBPUFxca5cYcUjr30917rVsHcNeWwMF/trkzuJrrJrVcSxCyMgsppVcDSiM+pBd0Ryi0NwFB2wyiA//IG2mwQMCCso7x6dfPi5olJSNUMb/PDYcM9mv+q4LDi89vJ6u3uEZFztIMfSJsJkVRYc3kk4jZ42nw6PnXq71zZzBUMxBzL6lTb3vLC2FLhbze6+o9Bfrw/NwZPDy+HxhowU9XAajJBotgIR6yDLJd9cUzp60OG9MkmrwVO3hWf5TftmFUsYjqEqZ2ukJ1vAPYK8mNRrk6/INz8oOyvCpLC9mEN33oWBs=,iv:tcrjYjDT2b+wgLHyU7QvOK1Vw65pFHeXB0wHrW7oD+4=,tag:K2o0BmXnt4uZrKEROIy8pQ==,type:str]
sops:
  azure_kv:
    - vault_url: https://sops-master.vault.azure.net
      name: sops-key
      version: 90784f2986de4514934b4d1f682d3e59
      created_at: "2026-04-02T09:12:25Z"
      enc: I6DaYKps79c7OZxywgXrw3pRQ-dld5VrAUJ6XF-MSO84AYtlMTSDlMvNGPF_xNIasUDmYBfmALk3XQUWGvBlBz24iUjRJ_eFsIgeeiH2YXlMbFguMIdm5DTn1HQYQTdDQyR1QBYHLQ1MhvNZbV7SDI57OeVxjkGtPIFWpcaQBjLNnzs0gDYp2Pw01H2gFJhpcfZgXjrAe1o0ToP58gK8DSThSx6geCgWm_msr08IjPD-nntteqfKUFQlnp87ihM32-OMFQdfo34GKNVFujswj00O150HJPYj7xKiP7G21M7fN2PI--6z5BEl8W_KX89TYpu6EMG3WL9D7r1vxHn4UQ
  lastmodified: "2026-04-02T09:12:26Z"
  mac: ENC[AES256_GCM,data:/P/ojb6JvtKIEILc1Zat8jeEmbWQJ9q8BnL65m99WPNBe3ZGD0Yi/VeOvbbiJKfQt8xAUPtOBCwdIABWQKNQi8gT11HY+93QwyIstvOvmeEzkhAgN6aJZzNJBhAwqyCLoY4JIS5qpG0LC2qB8WEpdS4xbiHUHr+oA097CxiNOD0=,iv:oFwgmszluMVVPrh4DEN/jBCN4xH28dSNWDg3PQdHEus=,tag:AydnTeidsjHmg0IHpjhemw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
