# yaml-language-server: $schema=./values.schema.json
namespace: crossplane-system
providerConfigName: github
members:
  - username: tahminator
    role: admin
  - username: arklian
    role: admin
  - username: Arshadul-Monir
    role: member
