# yaml-language-server: $schema=./values.schema.json
namespace: crossplane-system
providerConfigName: github
members:
  - username: tahminator
    role: admin
  - username: arklian
    role: admin
  - username: Arshadul-Monir
    role: member
  - username: SelinaZhu26
    role: member
  - username: Allimonae
    role: member
  - username: RandyJDean
    role: member
  - username: rootandroo
    role: member
  - username: isabellalam12
    role: member
  - username: MalihaT111
    role: member
