# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: infrastructure
spec:
  instances: 1
  # TODO: Decide what we want to do in long term, 2 replicas or some downtime during node upgrades
  # cluster does not support surge, so this is the only solution at this affinity;
  # on the upside, downtime should be very minimal due to current AKS configurations
  enablePDB: false
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  storage:
    size: 12Gi
  resources:
    requests:
      memory: "512Mi"
      cpu: "125m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
  enableSuperuserAccess: true
  superuserSecret:
    name: postgres-creds
  bootstrap:
    initdb:
      database: postgres
      owner: postgres
      secret:
        name: postgres-creds
