{{- range $teamName, $team := .Values.teams }}
---
apiVersion: team.github.upbound.io/v1alpha1
kind: Team
metadata:
  name: {{ $teamName | lower }}
spec:
  forProvider:
    name: {{ $teamName }}
    privacy: {{ default "closed" $team.privacy }}
  providerConfigRef:
    name: {{ $.Values.providerConfigName }}
{{- end }}
