{{- range $teamName, $team := .Values.teams }}
{{- $teamResourceName := $teamName | lower }}
{{- range $team.members }}
---
apiVersion: team.github.upbound.io/v1alpha1
kind: TeamMembership
metadata:
  name: {{ printf "%s-%s" $teamResourceName (.username | lower) }}
spec:
  forProvider:
    role: {{ default "member" .role }}
    username: {{ .username }}
    teamIdRef:
      name: {{ $teamResourceName }}
  providerConfigRef:
    name: {{ $.Values.providerConfigName }}
{{- end }}
{{- end }}
