apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - repositories
  - reloader

# https://davidelettieri.it/2023/11/01/flux-and-sops-on-aks-with-workload-identity
patches:
  - path: patches/all-controllers-resources.yaml
  - path: patches/kustomize-controller-deployment.yaml
  - path: patches/kustomize-controller-service-account.yaml
